spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cement
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
  thymeleaf:
    check-template-location: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 关闭SQL日志
server:
  port: 8085

file:
  upload-dir: D:/test

rabbitmq:
  exchange: download.exchange
  queue: download.queue
  routing-key: download.task
  upload-exchange: upload.exchange
  upload-queue: upload.queue
  upload-routing-key: upload.task

swagger:
  api:
    title: Big-Event API
    version: v1
    description: API documentation for Big-Event project

# 前端自动启动配置
frontend:
  auto-start: true          # 是否自动启动前端服务
  port: 5173                # 前端服务端口
  path: static/myVue        # 前端项目路径
  open-browser: true        # 是否自动打开浏览器
