spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cement
    username: postgre
    password: postgre
  data:
    redis:
      host: localhost
      port: 6379


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8085

file:
  upload-dir: D:/test

rabbitmq:
  exchange: download.exchange
  queue: download.queue
  routing-key: download.task
  upload-exchange: upload.exchange
  upload-queue: upload.queue
  upload-routing-key: upload.task

swagger:
  api:
    title: Big-Event API
    version: v1
    description: API documentation for Big-Event project


